
package tn.dashboard.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DashboardPortype", targetNamespace = "http://ws.dashboard.tn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DashboardPortype {


    /**
     * 
     * @return
     *     returns java.util.List<tn.dashboard.ws.Etudiant>
     */
    @WebMethod
    @WebResult(name = "etudiantsInscrits", targetNamespace = "")
    @RequestWrapper(localName = "afficherEtudiantsInscrits", targetNamespace = "http://ws.dashboard.tn/", className = "tn.dashboard.ws.AfficherEtudiantsInscrits")
    @ResponseWrapper(localName = "afficherEtudiantsInscritsResponse", targetNamespace = "http://ws.dashboard.tn/", className = "tn.dashboard.ws.AfficherEtudiantsInscritsResponse")
    public List<Etudiant> afficherEtudiantsInscrits();

    /**
     * 
     * @param nouveauCompteDashboard
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "codeValidation", targetNamespace = "")
    @RequestWrapper(localName = "creerCompteDashBoard", targetNamespace = "http://ws.dashboard.tn/", className = "tn.dashboard.ws.CreerCompteDashBoard")
    @ResponseWrapper(localName = "creerCompteDashBoardResponse", targetNamespace = "http://ws.dashboard.tn/", className = "tn.dashboard.ws.CreerCompteDashBoardResponse")
    public int creerCompteDashBoard(
        @WebParam(name = "nouveauCompteDashboard", targetNamespace = "")
        Etudiant nouveauCompteDashboard);

    /**
     * 
     * @param numeroEtudiant
     * @return
     *     returns tn.dashboard.ws.Etudiant
     */
    @WebMethod
    @WebResult(name = "informationEtudiant", targetNamespace = "")
    @RequestWrapper(localName = "affichageInformationEtudiant", targetNamespace = "http://ws.dashboard.tn/", className = "tn.dashboard.ws.AffichageInformationEtudiant")
    @ResponseWrapper(localName = "affichageInformationEtudiantResponse", targetNamespace = "http://ws.dashboard.tn/", className = "tn.dashboard.ws.AffichageInformationEtudiantResponse")
    public Etudiant affichageInformationEtudiant(
        @WebParam(name = "numeroEtudiant", targetNamespace = "")
        Long numeroEtudiant);

    /**
     * 
     * @param codeValidation
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "numeroConfirmation", targetNamespace = "")
    @RequestWrapper(localName = "validerCompteDashBoard", targetNamespace = "http://ws.dashboard.tn/", className = "tn.dashboard.ws.ValiderCompteDashBoard")
    @ResponseWrapper(localName = "validerCompteDashBoardResponse", targetNamespace = "http://ws.dashboard.tn/", className = "tn.dashboard.ws.ValiderCompteDashBoardResponse")
    public int validerCompteDashBoard(
        @WebParam(name = "codeValidation", targetNamespace = "")
        int codeValidation);

}
