
package tn.dashboard.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyDashboardService", targetNamespace = "http://ws.dashboard.tn/", wsdlLocation = "http://localhost:18080/examen-2018-0.0.1-SNAPSHOT/MyDashboard?wsdl")
public class MyDashboardService
    extends Service
{

    private final static URL MYDASHBOARDSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYDASHBOARDSERVICE_EXCEPTION;
    private final static QName MYDASHBOARDSERVICE_QNAME = new QName("http://ws.dashboard.tn/", "MyDashboardService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/examen-2018-0.0.1-SNAPSHOT/MyDashboard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYDASHBOARDSERVICE_WSDL_LOCATION = url;
        MYDASHBOARDSERVICE_EXCEPTION = e;
    }

    public MyDashboardService() {
        super(__getWsdlLocation(), MYDASHBOARDSERVICE_QNAME);
    }

    public MyDashboardService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYDASHBOARDSERVICE_QNAME, features);
    }

    public MyDashboardService(URL wsdlLocation) {
        super(wsdlLocation, MYDASHBOARDSERVICE_QNAME);
    }

    public MyDashboardService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYDASHBOARDSERVICE_QNAME, features);
    }

    public MyDashboardService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyDashboardService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DashboardPortype
     */
    @WebEndpoint(name = "DashboardPort")
    public DashboardPortype getDashboardPort() {
        return super.getPort(new QName("http://ws.dashboard.tn/", "DashboardPort"), DashboardPortype.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DashboardPortype
     */
    @WebEndpoint(name = "DashboardPort")
    public DashboardPortype getDashboardPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.dashboard.tn/", "DashboardPort"), DashboardPortype.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYDASHBOARDSERVICE_EXCEPTION!= null) {
            throw MYDASHBOARDSERVICE_EXCEPTION;
        }
        return MYDASHBOARDSERVICE_WSDL_LOCATION;
    }

}
