
package tn.greeting;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "greetingPortype", targetNamespace = "http://greeting.tn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GreetingPortype {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "greeting", targetNamespace = "")
    @RequestWrapper(localName = "greetingOperation", targetNamespace = "http://greeting.tn", className = "tn.greeting.GreetingOperation")
    @ResponseWrapper(localName = "greetingOperationResponse", targetNamespace = "http://greeting.tn", className = "tn.greeting.GreetingOperationResponse")
    public String greetingOperation();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "greetingTo", targetNamespace = "")
    @RequestWrapper(localName = "greetingToOperation", targetNamespace = "http://greeting.tn", className = "tn.greeting.GreetingToOperation")
    @ResponseWrapper(localName = "greetingToOperationResponse", targetNamespace = "http://greeting.tn", className = "tn.greeting.GreetingToOperationResponse")
    public String greetingToOperation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
